### ISSUE TITLE
Typos in userChrome.css (chrome/userChrome.css)

### ISSUE THREAD

**Issue by neniuk** [Godiesc/DiamondFucsia#1]
### Current: 
`  > .blocked-permission-icon {  height: 14px !important; width :14px !important; margin: 1px !important; padding: 0px !mportant}`

### Fixed: 
`  > .blocked-permission-icon {  height: 14px !important; width :14px !important; margin: 1px !important; padding: 0px !important}`

### Current:
`#urlbar-background{margin-block: 1px 1px; !important;}`

### Fixed:
`#urlbar-background{margin-block: 1px 1px !important;}`

**Comment by Godiesc** [comment]
Thanks for the report.
